version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    image: dinopedia
    environment:
      APP_DEBUG_MODE: "True"
      POSTGRES_HOST: django-dino.cmpkpzjgafgz.eu-south-1.rds.amazonaws.com
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: djangodino
      POSTGRES_PASSWORD: djangodino1
    entrypoint: ""
    command: "python dinopedia/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./dinopedia:/usr/dinopedia/app/dinopedia
      - ./tests:/usr/dinopedia/app/tests
      - ./pyproject.toml:/usr/dinopedia/app/pyproject.toml
      - ./poetry.lock:/usr/dinopedia/app/poetry.lock
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: djangodino1
    ports:
      - 5432:5432
